"""empty message

Revision ID: 2e20fd0d5883
Revises: 6107dfae376e
Create Date: 2026-08-27 09:30:07.989214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e20fd0d5883'
down_revision: Union[str, Sequence[str], None] = '6107dfae376e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('plan', sa.Enum('BASIC', 'PRO', name='statuschoices'), nullable=False))
    op.drop_column('user_profile', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('status', sa.VARCHAR(length=5), nullable=False))
    op.drop_column('user_profile', 'plan')
    # ### end Alembic commands ###
