"""empty message

Revision ID: 3c1389fb4690
Revises: 4bd3fa871cd6
Create Date: 2026-08-27 14:25:35.115153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1389fb4690'
down_revision: Union[str, Sequence[str], None] = '4bd3fa871cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_message', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('role', sa.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
