"""empty message

Revision ID: 4bd3fa871cd6
Revises: 49d10e2dc9d5
Create Date: 2026-08-27 10:29:51.883459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd3fa871cd6'
down_revision: Union[str, Sequence[str], None] = '49d10e2dc9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('message', sa.Text(), nullable=False))
    op.add_column('chat_message', sa.Column('response', sa.String(), nullable=False))
    op.drop_column('chat_message', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('content', sa.TEXT(), nullable=False))
    op.drop_column('chat_message', 'response')
    op.drop_column('chat_message', 'message')
    # ### end Alembic commands ###
