"""empty message

Revision ID: b74c8e3fe6ac
Revises: 2e20fd0d5883
Create Date: 2026-08-27 09:34:45.895818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74c8e3fe6ac'
down_revision: Union[str, Sequence[str], None] = '2e20fd0d5883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('plan', sa.Enum('BASIC', 'PRO', name='statuschoices'), server_default='Basic', nullable=False))
    op.drop_column('user_profile', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('status', sa.VARCHAR(length=5), nullable=False))
    op.drop_column('user_profile', 'plan')
    # ### end Alembic commands ###
